### ISSUE TITLE
работа через прокси

### ISSUE THREAD

**Issue by BlackWarriorNT** [seniv/vk-tg-bot#11]
Можно добавить возможность работы через прокси-сервер?

**Comment by GigaVik** [comment]
Я на винде использовал TunnelBear. Но в теории можно использовать проксю исключительно для этого приложения, правила забиваются через строку.
Сейчас запустил бота на виртуальном сервере от амазон, точнее Amazon EC2. Работает все изумительно.

**Comment by BlackYuzia** [comment]
@BlackWarriorNT а не проще ли просто юзая VDS/VPS ?
т.е. бот работает, скажем, на русском IP.

Потому, он сможет свободно принимать и пересылать сообщения. 
???
**PROFIT**

**Comment by BlackWarriorNT** [comment]
@BlackYuzia просто использую местный прокси для телеги. Так что, VDS/VPS -- не проще)
