### ISSUE TITLE
[REQ] Цитирование | Reply

### ISSUE THREAD

**Issue by BlackYuzia** [seniv/vk-tg-bot#12]
@seniv 
Можно ли просматривать "reply"? 
Хотелось бы видеть на что отвечает человек (который пишет в ВК) тебе, а также, что бы если ты "цитируешь" какое-либо сообщение из телеги, оно отсылалось и в ВК (на счет последнего не уверен. Но вот "цитата" с ВК вроде точно можно "ловить")

**Comment by GigaVik** [comment]
Пробовал отправлять цитату в бота в котором заведомо выбран адресат?

**Comment by BlackYuzia** [comment]
@GigaVik Да.
Все равно не пашет.

**Comment by seniv** [comment]
https://github.com/seniv/vk-tg-bot/issues/14 Я тут написал несколько ответов на наши вопросы

**Comment by seniv** [comment]
Обновил бота, теперь он поддерживает цитирование.
Подробнее сдесь https://github.com/seniv/vk-tg-bot/issues/14#issuecomment-392336672
