### ISSUE TITLE
ℹНа счет обновлений бота и фикса описаных Вами проблем

### ISSUE THREAD

**Issue by seniv** [seniv/vk-tg-bot#14]
Так как ВК я уже давно не пользуюсь - желания и смысла обновлять бот у меня не очень много.
Но я вижу что есть не мало людей которым этот бот интересен(чего я даже не ожидал), и я постараюсь немного доделать бота: обновить все зависимости бота до последних версий, сделать поддержку цитат ну и исправить описаные вами проблемы.
Надеюсь сделать все это до конца следующей недели.

Если у вас есть хоть небольшие знания JS - вы и сами сможете без проблем сделать поддержку вообше всего что есть в ВК (не без костылей конечно, но по сути это возможно)
Все что вам для этого нужно знать это [Telegraf](https://telegraf.js.org/#/) - фреймворк на котором написан бот, и [vk-io](https://github.com/negezor/vk-io) - либа которую я использовал для VK API.

Если кто-то надумает что-то обновлять - [Pull request](https://github.com/seniv/vk-tg-bot/pulls)'ы приветствуются, их я буду проверять чаще чем делать апдейты😃

**Comment by GigaVik** [comment]
Это очень хорошая новость. Сам бы уже снес ВК. но раз в пол года (на сессию) он нужен. Все оф группы с данными по курсу находятся в вк.
Я только начинающий, знакомлюсь с языками. Рук и головы хватает чтобы поднять бота на сервере/ПК и что то подправить в нем. но не хватает чтобы самому написать даже маленький кусок кода.

**Comment by seniv** [comment]
Только-что обновил бота, переписал примерно половину кода, как и обещал - обновил пакеты до последних версий, Сделал поддержку пересланых сообщение( в том числе ответов на сообщения ), исправил проблему с командой **/online**, Добавил две новые команды:
1. **/friendson**  - Список друзей онлайн
2. **/history**  - Загрузить историю сообщений с выбраным пользователем, вклучая все вложения и пересланые сообщения
Также теперь бот принимает документы из ВК(гифки, файлы, архивы).
Еще я улучшил разбор вложений из ВК, хотя возможно это не будет заметно.

Чтобы обновить бота нужно ввести `git pull`(хотя не доконца уверен в этом, в любом случаи можете просто склонировать репозиторий еще раз) в папке с ботом и обновить пакеты `npm i`, если вы скачивали его через git. Или просто перекачайте архив с ботом

Новая версия бота тестировалась на NodeJS версии 10.0.0, так что убедитесь что у вас версия не ниже этой

**Comment by BlackYuzia** [comment]
Нашел баг. Подробнее в #19
