### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by BlackWarriorNT** [seniv/vk-tg-bot#17]
`root@majordomo:~/vk-tg-bot#  "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/telegraf
npm http GET https://registry.npmjs.org/vk-io
npm http GET https://registry.npmjs.org/webp-converter
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/moment-timezone
npm http GET https://registry.npmjs.org/vk-io
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/telegraf
npm http GET https://registry.npmjs.org/webp-converter
npm http GET https://registry.npmjs.org/moment-timezone
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/telegraf
npm http GET https://registry.npmjs.org/vk-io
npm http GET https://registry.npmjs.org/webp-converter
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/vk-tg-bot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http GET https://registry.npmjs.org/moment-timezone
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/moment
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/vk-tg-bot/npm-debug.log
npm ERR! not ok code 0
`

**Comment by seniv** [comment]
Похоже у тебе очень древний NodeJS.
Обнови NodeJS и NPM до последних версий, должно помочь
