### ISSUE TITLE
[BUG&&REQ] Баг с /History | Не показывает товары

### ISSUE THREAD

**Issue by BlackYuzia** [seniv/vk-tg-bot#19]
@seniv 

# Проблема с Товарами
 Если кто-то пишет по поводу товара (из магазина) то я ловлю следующее:
![2018-05-28_120538](https://user-images.githubusercontent.com/25010528/40606987-cdff6cbe-626f-11e8-8482-b19c9822ba42.png)
Как бы мелочь, а нужно. Приходится спрашивать "_че ты хочешь peedor?_"
# Баг с "Хистори"
И мне кажется я нашел баг.... при вводе **/history**
![2018-05-28_120557](https://user-images.githubusercontent.com/25010528/40606905-898e2cb4-626f-11e8-83ee-6724fc48149a.png)
Сообщения которые вводил другой человек, выводит как будто это писал Я. Хотя, (если зайти в ВК и посмотреть) это писал ОН. (т.е. тот чел с кем я щяс общаюсь, и он выбран через **/xxxxxx**).

Ну а сообщения которые писал уже Я, выводит как будто пишет ОН.
![2018-05-28_121807](https://user-images.githubusercontent.com/25010528/40607477-502bae22-6271-11e8-82b2-684edf488572.png)

**Comment by seniv** [comment]
Баг с историей пофиксил.
А вот "market" приходит в бот как вложение, и для него нужно сделать обработчик. Но делать его я точно не буду.

**Comment by BlackYuzia** [comment]
А за донатик? :d 
(_я просто не на столько нодер что бы делать обработчик для того, что я даже не знаю как работает_)
