### ISSUE TITLE
[BUG] .GIF не отправляются

### ISSUE THREAD

**Issue by BlackYuzia** [seniv/vk-tg-bot#22]
@seniv не знаю должны ли гифки отправляться в VK. 
Но, после ряда попыток, через телеграмм в ВК, они (гифки) не хотят отправляться. Стикеры и фото - да. Гифки - нет.

Специально тестанул с ласт версией. Все также.

**Comment by seniv** [comment]
Это не баг, а фича. А точнее её отсутствие. 😏
Отправку гифок и других документов из телеграма я еще не делал.
