### ISSUE TITLE
[REQ] Edit Msg

### ISSUE THREAD

**Issue by BlackYuzia** [seniv/vk-tg-bot#29]
@seniv есть очень большая надобность в возможности редактировать уже отправленное сообщение.
:thinking: 

Но делать это, конечно же, ты не будешь. :eyes: 
Чаво будем делать? :smiley:

**Comment by haswelldev** [comment]
Можно было бы сделать, но фича сложнее чем кажется, для нормальной реализации нужно будет прикручивать хранилище данных и хранить связи между сообщениями из вк и телеги. А желательно ещё и версионность самих сообщений делать...

**Comment by BlackYuzia** [comment]
@421p а если костыли?
Просто удалять "старое" сообщение, отсылать "новое".

Но в таком случае фича будет работать только с последним отправленным.
