### ISSUE TITLE
Очень неполный гайд =(

### ISSUE THREAD

**Issue by StirliX** [seniv/vk-tg-bot#3]

**Comment by StirliX** [comment]
Ничего не понятно после получения access_token (кстати не работало в мозилле, заработало в хроме)
всё самому допирать, ну скачал в итоге Гит, открыл git cmd. Первая команда и вторая работают, попал в папку с ботом. 
npm install - не работает. куда её писать то?
node tkbot.js - не работает.

**Comment by seniv** [comment]
Я так понимаю у тебя нету [NodeJS](https://nodejs.org/en/), поэтому не работает `npm install`.

На счет того что гайд не очень понятний - это потому что он рассчитан на тех кто уже знаком с Git, JS и NodeJS. Хотя Git и не обязателен, можно было просто [скачать репозиторий архивом](https://github.com/seniv/vk-tg-bot/archive/master.zip).

**Comment by StirliX** [comment]
Ну поставил NodeJS всё заработало, встало, наслаждаюсь ботом. 
Спасибо! Бот реально классный.
Но гайд я бы дополнил. Необходимыми установщиками, и добавил бы в описание что бот работает на компе и должен быть всегда включен. Чтобы люди понимали сразу что им необходимо и могут ли они это предоставить. Для меня это перый бот, поэтому я например не знал ничего о том как и главное где они работают.

**Comment by seniv** [comment]
Врядли я найду время и желание чтобы дополнить описание, но всякое может быть.🙂

И кстати, ты можеш поставить бота на сервер(VPS/VDS/Dedicated) чтобы но постоянно работал
