### ISSUE TITLE
Доработка

### ISSUE THREAD

**Issue by liveinno** [seniv/vk-tg-bot#34]
Никогда не сталкивался с nodejs, разобратся не могу.
Сколько будет стоить доработать бота? Добавить поддержку работы в групповых чатах, режимы приватности(списки id, возможность добавления id юзеров телеги которые имеют право писать), доработать reply сейчас они не очень хорошо работают

**Comment by BlackYuzia** [comment]
Вроде как автор заявлял что ни за какие ~~шиши~~ **Money** не будет его обновлять ибо ему надоело. :eyes: 

Вроде как @421p в последнее время активно дорабатывает. Спроси у него.

**Comment by haswelldev** [comment]
AFAIK у проекта нету dedicated мэйнтейнера, что автор что я докручиваем фичи в свободное время, больших апдейтов ждать не стоит
