### ISSUE TITLE
Не будет работать

### ISSUE THREAD

**Issue by telema93** [seniv/vk-tg-bot#37]
Короче, они отключили API сообщений и приложение не сможет работать, тк нельзя получить токен для сообщений. Ну и покойся с миром вкшечка, уже все давно в телеграм

**Comment by techiedesu** [comment]
@telema93, не обязательно использовать своё ВК приложение, можно взять от Kate Mobile. Попробуйте `client_id` указать `2685278`.

**Comment by MxDeWitt** [comment]
После попытки авторизации standalone приложения выпадает ошибка:

```{"error":"invalid_request","error_description":"This application has no right to use messages"}```

Вероятно, как раз эффект упомянутого выше отсутствия доступа.

Если вместо ```client_id ``` указать ```2685278```, выпадает пустая страница с единственной строчкой:

```Пожалуйста, не копируйте данные из адресной строки для сторонних сайтов. Таким образом Вы можете потерять доступ к Вашему аккаунту.```

**Comment by telema93** [comment]
Через Kate нормуль, берите ID 2685278 и будет вам счастье. Сам с вк тоже сехал, а так позволяет особо одаренным писать мне
