### ISSUE TITLE
помощь

### ISSUE THREAD

**Issue by marlboroboyy** [seniv/vk-tg-bot#5]
Привет! Немного потерялся в твоей инструкции , подскажи откуда скачать модуль npm install
так же я не понял где взять id telegramm и + ко всему этому у меня пишет ошибку приложение tkbot
Заранее спасибо!

**Comment by geak** [comment]
Тебе для этого нужно установить nodejs (если не установлен, конечно).

**Comment by seniv** [comment]
@marlboroboyy Как уже сказали, нужен nodejs. https://nodejs.org/en/
А получить telegram id можно введя боту комаду `/myid`, запустив бота перед этим, как написано в документации.

**Comment by ghost** [comment]
> А получить telegram id можно введя боту комаду /myid, запустив бота перед этим, как написано  > документации.

у меня кстати так не получилось, взял id у бота @userinfobot

**Comment by marlboroboyy** [comment]
может ли кто скинуть готовый образец бота уже со всеми загруженными модулями? вроде все понимаю но тут прям тупка идет , не получается запустить. Если есть такая возможность то скинте "шаблон" где только айдишник вбить придется , буду очень благодарен. Сама суть проблемы что не понимаю какой именно кинуть модуль , все скачал но там очень муторно для меня. Или хотябы этот модуль скиньте добрые люди!

**Comment by seniv** [comment]
@marlboroboyy Все что тебе нужно сделать это установить nodejs(если ещё нет), открыть Terminal/PowerShell/Командную строку в папке с ботом и напасать `npm install`.
Если не получится - пиши, скину бота с уже установленными модулями

**Comment by marlboroboyy** [comment]
спасибо большое , разобрался и оказывается по началу вообще не вдуплил как это делать , скачал много чего (тоже не без помощи) , бот клевый , спасибо!
