### ISSUE TITLE
Проблема с запуском бота

### ISSUE THREAD

**Issue by ponydozer** [seniv/vk-tg-bot#8]
При включении бота выдает такую ошибку:
iMac-Daniila:vk-tg-bot daniiluglov$ node tkbot.js
internal/modules/cjs/loader.js:676
    throw err;
    ^

SyntaxError: /Users/daniiluglov/vk-tg-bot/config.json: Unexpected token / in JSON at position 184
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:673:27)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/daniiluglov/vk-tg-bot/tkbot.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

Скорее всего это я что-то не правильно сделал, но вот что, я не знаю. 
Заранее спасибо за помощь.

**Comment by seniv** [comment]
@ponydozer А какая версия nodejs?
`node -v` чтобы посмотреть

**Comment by ponydozer** [comment]
@seniv v9.11.1

**Comment by seniv** [comment]
Скорее всего ты что-то не так в файле `config.json` написал, проверь может кавычку где-то не поставил

**Comment by ponydozer** [comment]
@seniv Не могли бы ли Вы сказать, что именно, т.к. я слабо в это разбираюсь? (токены я изменил)
{
  "vk_token": "4c60614573bedaea44d30845a7874138e4e0989831f0f6e206dbd99566468240c1c7b95a4d9fb4ee0f58e",
  "tg_token": "574307029:AAGKMKuAc8YIAi2TsZnXfKXElWfCdoHpbMo",
  "tg_user": 0, // 255845815
  "keyboard": [
    ["/online", "/friends"]
  ]
}

**Comment by seniv** [comment]
Попробуй удалить коментарий в строке `tg_user` (// 255845815)

**Comment by ponydozer** [comment]
@seniv Все равно не работает
iMac-Daniila:vk-tg-bot daniiluglov$ node tkbot.js
Long Poll is started
Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU2Ts890fKXElWfCdoHpbMo/getUpdates?offset=836512536&limit=100&timeout=30 failed, reason: read ECONNRESET
Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU2Ts980KXElWfCdoHpbMo/getUpdates?offset=836512536&limit=100&timeout=30 failed, reason: read ECONNRESET
Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU2Ts978KXElWfCdoHpbMo/getUpdates?offset=836512536&limit=100&timeout=30 failed, reason: read ECONNRESET
Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU987XfKXElWfCdoHpbMo/getUpdates?offset=836512536&limit=100&timeout=30 failed, reason: read ECONNRESET
Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU2T987fKXElWfCdoHpbMo/getUpdates?of

**Comment by seniv** [comment]
Возможно у тебя проблемы с соединением к телеграму?

**Comment by Slabkiy** [comment]
> @seniv Все равно не работает
> iMac-Daniila:vk-tg-bot daniiluglov$ node tkbot.js
> Long Poll is started
> Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU2Ts890fKXElWfCdoHpbMo/getUpdates?offset=836512536&limit=100&timeout=30 failed, reason: read ECONNRESET
> Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU2Ts980KXElWfCdoHpbMo/getUpdates?offset=836512536&limit=100&timeout=30 failed, reason: read ECONNRESET
> Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU2Ts978KXElWfCdoHpbMo/getUpdates?offset=836512536&limit=100&timeout=30 failed, reason: read ECONNRESET
> Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU987XfKXElWfCdoHpbMo/getUpdates?offset=836512536&limit=100&timeout=30 failed, reason: read ECONNRESET
> Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot574307029:AAGKMKuAc8YIAU2T987fKXElWfCdoHpbMo/getUpdates?of

нужно установить пакет `npm install --save socks5-https-client`

добавить код 

```
const SocksAgent = require('socks5-https-client/lib/Agent');
const socksAgent = new SocksAgent({
  socksHost: config.proxy.host,
  socksPort: config.proxy.port,
  socksUsername: config.proxy.login,
  socksPassword: config.proxy.psswd,
});

```
изменить подключение к **Telegraf**
```
const app = new Telegraf(config.tg_token, {
  telegram: { agent: socksAgent }
});
```
